# -*- coding: utf-8 -*-
"""TrainYolov8CustomDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s035bjUbURCzLEed2fs-GIjiuaHauAON
"""

from google.colab import drive

drive.mount('/content/gdrive')

ROOT_DIR = '/content/gdrive/My Drive/ComputerVisionDeveloper/TrainYolov8CustomDataset'

!pip install ultralytics

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="IVazsWNNWJbj8YtUCB2b")
project = rf.workspace("first-2u8hl").project("mars-rocks")
version = project.version(2)
dataset = version.download("yolov8")

import os

from ultralytics import YOLO


# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model.train(data="/content/Mars-Rocks-2/data.yaml", epochs=75)  # train the model

!python detect.py --weights /content/runs/detect/train/weights/best.pt --conf 0.7 --source /content/Mars-Rocks-2/Mars-Rocks-2/test/images

!scp -r /content/runs '/content/gdrive/My Drive/ComputerVisionDeveloper/TrainYolov8CustomDataset'